services:
     video.twig.app_extension:
                class: VideoBundle\Twig\AppExtension
                arguments: ['@doctrine']
                tags:
                    -  { name: twig.extension }
